// Autogenerated by font_data.awk
var _font_map = {
  serif1: {
    h: 'simonetta',
    p: 'andada',
  },
  mono1: {
    p: 'office_code_pro_dmedium',
  },
  serif2: {
    h: 'simonetta',
    p: 'playfair_display',
  },
  mono2: {
    p: 'm_1mmedium',
  },
  sans1: {
    h: 'amaranth',
    p: 'amble',
  },
  sans2: {
    h: 'amaranth',
    p: 'blogger_sans',
  },
};
var _font_data = {
  playfair_display: {
    regular: 'playfair_displayregular',
    italic: 'playfair_displayitalic',
    bolditalic: 'playfair_displaybold_italic',
    bold: 'playfair_displaybold',
  },
  blogger_sans: {
    regular: 'blogger_sansregular',
    italic: 'blogger_sansitalic',
    bolditalic: 'blogger_sansbold_italic',
    bold: 'blogger_sansbold',
  },
  amble: {
    regular: 'ambleregular',
    italic: 'ambleitalic',
    bolditalic: 'amblebold_italic',
    bold: 'amblebold',
  },
  m_1mmedium: {
    regular: 'm_1mmedium',
  },
  simonetta: {
    regular: 'simonettaregular',
    italic: 'simonettaitalic',
    bolditalic: 'simonettablack_italic',
    bold: 'simonettablack',
  },
  office_code_pro_dmedium: {
    regular: 'office_code_pro_dmedium',
  },
  amaranth: {
    regular: 'amaranthregular',
    italic: 'amaranthitalic',
    bolditalic: 'amaranthbolditalic',
    bold: 'amaranthbold',
  },
  andada: {
    regular: 'andadaregular',
    italic: 'andadaitalic',
    bolditalic: 'andadabold_italic',
    bold: 'andadabold',
  },
};
