# Usage: awk -f font_data.awk */*.css > font_data.js

BEGIN {
    print "// Generated by font_data.awk\n"

    for(i = 1; i < ARGC; i++) {
        imports[ARGV[i]] = 1;
    }
}


/font-family: '[a-zA-Z_0-9]+'/ {

    split($0, arr, "'");
    font = arr[2];
    class = font;
    style = font;

    sub(/(_?bold|_?italic|_?bold_?italic|_?regular|_?black|_?black_?italic|_?semi)/, "", class);

    gsub(/_/, "", style)
    sub(/bold_?italic/, "ASDF", style);
    sub(/black_?italic/, "ASDF", style);
    sub(/.*regular/, "regular", style);
    sub(/.*light/, "regular", style);
    sub(/.*medium/, "regular", style);
    sub(/black/, "bold", style)
    sub(/.*bold/, "bold", style);
    sub(/.*italic/, "italic", style);
    sub(/semi/, "", style);
    sub(/.*ASDF/, "bolditalic", style);

    fonts[class] = 1
    output[class "-" style] = font
}


END {
    styles["bold"] = 1;
    styles["bolditalic"] = 1;
    styles["italic"] = 1;
    styles["regular"] = 1;

    print "var _font_data = {";

    for(class in fonts) {
        print "  " class ": {";

        for(style in styles) {
            if(output[class "-" style] != "") {

                print "    " style ": '" output[class "-" style] "',"
            }
        }
        print "  },"
    }
    print "};"
}

