# ------------------------------------------------------------------------------
# Example MyServer configuration
---
Databases:
  default:
    Assembly: httplib.db.mysql.dll
    Typename: httplib.db.MySqlDatabase
    Connection: server=localhost;userid=user12;password=34klq*;database=mydb
Prefixes:
  Secure:
    - https://localhost:8443/
  Insecure:
    - http://localhost:8080/
Roots:
  - www
  - ../../contrib/client
Compression:
  - gzip
  - deflate
FileServing:
  /.*css: { Cache-Control: "public, max-age=86400" }
  /.*html: { Cache-Control: "no-cache" }
  /.*js: { Cache-Control: "private, max-age=86400" }
  /.*ttf: { Cache-Control: "public, max-age=31536000" }
  /.*woff: { Cache-Control: "public, max-age=31536000" }
  /.*woff2: { Cache-Control: "public, max-age=31536000" }
  /.*png: { Cache-Control: "public, max-age=86400" }
  /edit: { Cache-Control: "no-cache" }
  /magic: { Cache-Control: "no-cache" }
  /script: { Cache-Control: "no-cache" }
  /test[0-9]+: { Cache-Control: "no-cache" }
  /upload: { Cache-Control: "no-cache" }
Renderers:
  yml:
    Assembly: httplib.dll
    Typename: httplib.Renderer
  nyml:
    Assembly: httplib.page.nustache.dll
    Typename: httplib.page.NustacheRenderer
Modules:
  MyTestModule:
    Assembly: http.exe
    Typename: MyTestModule
  MyTestModule2:
    Assembly: http.exe
    Typename: MyTestModule
    Data:
      Text: This is some text from the second instance of MyTestModule.
  Pbkdf2Auth:
    Assembly: httplib.mod.auth.dll
    Typename: httplib.mod.Pbkdf2Auth
    Data:
      IterationCount: 300
      HashLength: 25
  BbCode:
    Assembly: httplib.mod.bbcode.dll
    Typename: httplib.mod.BbCode
    Data:
      Tags:
        - { Tag: "b", Open: "<b>", Close: "</b>" }
        - { Tag: "i", Open: "<i>", Close: "</i>" }
        - { Tag: "u", Open: "<u>", Close: "</u>" }
        - { Tag: "s", Open: "<s>", Close: "</s>" }
        - { Tag: "tt", Open: "<tt>", Close: "</tt>" }
        - { Tag: "h1", Open: "<h1>", Close: "</h1>" }
        - { Tag: "h2", Open: "<h2>", Close: "</h2>" }
        - { Tag: "h3", Open: "<h3>", Close: "</h3>" }
        - { Tag: "h4", Open: "<h4>", Close: "</h4>" }
        - { Tag: "h5", Open: "<h5>", Close: "</h5>" }
        - { Tag: "h6", Open: "<h6>", Close: "</h6>" }
        - { Tag: "code", Open: "<pre>", Close: "</pre>" }
        - { Tag: "img", Open: "<img src='${content}'/>", Close: "", Flags: "NoAutoRender" }
        - { Tag: "quote", Open: "<blockquote>", Close: "</blockquote>" }
        - { Tag: "list", Open: "<ul>", Close: "</ul>" }
        - { Tag: "ul", Open: "<ul>", Close: "</ul>" }
        - { Tag: "ol", Open: "<ol>", Close: "</ol>" }
        - { Tag: "li", Open: "<li>", Close: "</li>" }
        - { Tag: "*", Open: "<li>", Close: "</li>", Flags: "NoClose" }
        - { Tag: "url", Open: "<a href='${href}'>", Close: "</a>",
            Attrs: [ { Id: "href", Name: "" }, { Id: "href", Name: "href" } ] }
  HtmlSan:
    Assembly: httplib.mod.htmlsanitize.dll
    Typename: httplib.mod.HtmlSanitizer
  ImageProcessor:
    Assembly: httplib.mod.imageprocessor.dll
    Typename: httplib.mod.ImageProcessorFactory
    Data:
      Operations:
        white-bg: { op: BackgroundColour, r: 255, g: 255, b: 255, a: 255 }
        entropycrop: { op: EntropyCrop, threshold: 128 }
        resize40: { op: Resize, x: 40, y: 40 }
        resize64: { op: Resize, x: 64, y: 64 }
        resize80: { op: Resize, x: 80, y: 80 }
        resize120: { op: Resize, x: 120, y: 120 }
      Transforms:
        avatar40: [ white-bg, entropycrop, resize40 ]
        avatar64: [ white-bg, entropycrop, resize64 ]
        avatar80: [ white-bg, entropycrop, resize80 ]
        avatar120: [ white-bg, entropycrop, resize120 ]
  Smtp:
    Assembly: httplib.mod.smtp.dll
    Typename: httplib.mod.Smtp
    Data:
      Host: localhost
      Port: 25
  Textile:
    Assembly: httplib.mod.textile.dll
    Typename: httplib.mod.Textile
MimeTypes:
  js: application/javascript
  json: application/json
  html: text/html
  css: text/css
  ttf: application/x-font-ttf
  woff: application/x-font-woff
  woff2: application/octet-stream
  _: text/plain
OutputLength: 800
FileChunkLength: 1024
ForceInsecureOperation: false
Logging:
  Assembly: httplib.log.nlog.dll
  Typename: httplib.log.NLogLogging
  Targets:
    console:
      Type: ColoredConsoleTarget
      Layout: "${message}"
      Colours: { Debug: DarkGreen, Info: Green, Warn: DarkYellow }
    file:
      Type: FileTarget
      Path: "${basedir}/http-${date:format=yyyy.MM.dd-HH.mm.ss:cached=true}.log"
      Layout: "${date:format=HH\\:mm\\:ss} ${logger} ${message}"
  Rules:
    - { Source: "*", Level: Trace, Target: console }
    - { Source: "*", Level: Info, Target: file }
