# ------------------------------------------------------------------------------
# Example forum.exe configuration
---
SiteName: myforum.com
DefaultAvatarImage: avatar-tiny.png
DefaultEmailSender: webmaster@example.com
DefaultFontClass: serif1
DefaultColourClass: x360
DefaultTransform: bbcode
AccountRecovery:
  EmailSender: nobody@example.com
  EmailBody: recovery-email.nyml
  LevenshteinThreshold: 3
Databases:
  default:
    Assembly: httplib.db.mysql.dll
    Typename: httplib.db.MySqlDatabase
    Connection: server=localhost;userid=forum;password=n0ts3cr3t;database=forum;charset=utf8
StripPortFromDefaultPrefixes: false
Prefixes:
  Secure:
    - https://127.0.0.1:8443/
  Insecure:
    - http://localhost:8080/
Roots:
  - ../../bin/cache/forum
  - www
  - ../../contrib/client
  - ../../contrib/fonts
Compression:
  - gzip
  - deflate
Consolidation:
  CachePath: ../../bin/cache/forum
  Types:
    Scripts: min
    Stylesheets: min
FileServing:
  /.*css: { Cache-Control: "public, max-age=86400" }
  /.*html: { Cache-Control: "no-cache" }
  /.*ico: { Cache-Control: "public, max-age=31536000" }
  /.*js: { Cache-Control: "private, max-age=86400" }
  /.*map: { Cache-Control: "public, max-age=86400" }
  /.*png: { Cache-Control: "public, max-age=86400" }
  /.*ttf: { Cache-Control: "public, max-age=31536000" }
  /.*woff: { Cache-Control: "public, max-age=31536000" }
  /.*woff2: { Cache-Control: "public, max-age=31536000" }
Renderers:
  yml:
    Assembly: httplib.dll
    Typename: httplib.Renderer
  nyml:
    Assembly: httplib.page.nustache.dll
    Typename: httplib.page.NustacheRenderer
Modules:
  Filter:
    Assembly: forum.mod.filter.dll
    Typename: forum.mod.Filter
    Data:
      Filters:
        - { Search: "first post", Replace: "lame", Flags: "Boundary" }
        - { Search: "frist post", Replace: "lamer", Flags: "IgnoreCase|Boundary" }
        - { Search: "cock", Replace: "rooster", Flags: "IgnoreCase" }
        - { Search: "string", Replace: "chord", Flags: "IgnoreCase" }
  Pbkdf2Auth:
    Assembly: httplib.mod.auth.dll
    Typename: httplib.mod.Pbkdf2Auth
    Data:
      IterationCount: 25000
      HashLength: 40
  BbCode:
    Assembly: httplib.mod.bbcode.dll
    Typename: httplib.mod.BbCode
    Data:
      Tags:
        - { Tag: "b", Open: "<b>", Close: "</b>" }
        - { Tag: "i", Open: "<i>", Close: "</i>" }
        - { Tag: "u", Open: "<u>", Close: "</u>" }
        - { Tag: "s", Open: "<s>", Close: "</s>" }
        - { Tag: "tt", Open: "<tt>", Close: "</tt>" }
        - { Tag: "h1", Open: "<h1>", Close: "</h1>" }
        - { Tag: "h2", Open: "<h2>", Close: "</h2>" }
        - { Tag: "h3", Open: "<h3>", Close: "</h3>" }
        - { Tag: "h4", Open: "<h4>", Close: "</h4>" }
        - { Tag: "h5", Open: "<h5>", Close: "</h5>" }
        - { Tag: "h6", Open: "<h6>", Close: "</h6>" }
        - { Tag: "code", Open: "<pre>", Close: "</pre>" }
        - { Tag: "img", Open: "<img src='${content}'/>", Close: "", Flags: "NoAutoRender" }
        - { Tag: "quote", Open: "<blockquote>", Close: "</blockquote>" }
        - { Tag: "q", Open: "<q>", Close: "</q>" }
        - { Tag: "cite", Open: "<cite>", Close: "</cite>" }
        - { Tag: "list", Open: "<ul>", Close: "</ul>" }
        - { Tag: "ul", Open: "<ul>", Close: "</ul>" }
        - { Tag: "ol", Open: "<ol>", Close: "</ol>" }
        - { Tag: "li", Open: "<li>", Close: "</li>" }
        - { Tag: "*", Open: "<li>", Close: "", Flags: "NoClose" }
        - { Tag: "br", Open: "<br>", Close: "", Flags: "NoClose"  }
        - { Tag: "hr", Open: "<hr>", Close: "", Flags: "NoClose"  }
        - { Tag: "url", Open: "<a href='${href}'>", Close: "</a>",
            Attrs: [ { Id: "href", Name: "" }, { Id: "href", Name: "href" } ] }
  HtmlSanitizer:
    Assembly: httplib.mod.htmlsanitize.dll
    Typename: httplib.mod.HtmlSanitizer
  ImageProcessor:
    Assembly: httplib.mod.imageprocessor.dll
    Typename: httplib.mod.ImageProcessorFactory
    Data:
      Operations:
        entropycrop: { op: EntropyCrop, threshold: 128 }
        resize40: { op: Resize, x: 40, y: 40 }
        resize64: { op: Resize, x: 64, y: 64 }
        resize80: { op: Resize, x: 80, y: 80 }
        resize120: { op: Resize, x: 120, y: 120 }
      Transforms:
        avatar40: [ resize40 ]
        avatar64: [ resize64 ]
        avatar80: [ resize80 ]
        avatar120: [ resize120 ]
        avatar40crop: [ entropycrop, resize40 ]
        avatar64crop: [ entropycrop, resize64 ]
        avatar80crop: [ entropycrop, resize80 ]
        avatar120crop: [ entropycrop, resize120 ]
  OEmbed:
    Assembly: httplib.mod.oembed.dll
    Typename: httplib.mod.OEmbed
    Data:
      Types:
        Bash:
          Assembly: forum.mod.providers.dll
          Typename: forum.mod.BashProvider
        OEmbedPhoto:
          Assembly: httplib.mod.oembed.dll
          Typename: httplib.mod.OEmbedPhotoProvider
        OEmbedRich:
          Assembly: httplib.mod.oembed.dll
          Typename: httplib.mod.OEmbedRichProvider
        OEmbedVideo:
          Assembly: httplib.mod.oembed.dll
          Typename: httplib.mod.OEmbedVideoProvider
        DefaultUrl:
          Assembly: httplib.mod.oembed.dll
          Typename: httplib.mod.DefaultUrlProvider
      Providers:
        - Name: Bash
          Type: Bash
          Patterns:
            - "http://(?:www\\.)?bash\\.org/\\?(\\d+)"
        - Name: Flickr
          Type: OEmbedPhoto
          Endpoint: "http://www.flickr.com/services/oembed"
          Patterns:
            - "https?://(?:www\\.)?flickr\\.com/.*"
            - "https?://flic\\.kr/p/[a-zA-Z0-9]+"
        - Name: QDB
          Type: Bash
          Patterns:
            - "http://(?:www\\.)?qdb.us/(\\d+)"
        - Name: SoundCloud
          Type: OEmbedVideo
          Endpoint: "http://soundcloud.com/oembed"
          Patterns:
            - "https?://soundcloud.com/.*/.*"
        - Name: TED
          Type: OEmbedVideo
          Endpoint: "http://www.ted.com/services/v1/oembed.json"
          Patterns:
            - "https?://www\\.ted\\.com/talks/.+"
        - Name: Twitter
          Type: OEmbedRich
          ExtraParams: "omit_script=1"
          Endpoint: "https://api.twitter.com/1/statuses/oembed.json"
          Patterns:
            - "https?://(?:www|mobile\\.)?twitter\\.com/(?:#!/)?[^/]+/status(?:es)?/(\\d+)/?$"
        - Name: Vimeo
          Type: OEmbedVideo
          Endpoint: "http://vimeo.com/api/oembed.json"
          Patterns:
            - "https?://(?:www\\.)?vimeo\\.com/.+"
        - Name: YouTube
          Type: OEmbedVideo
          Endpoint: "http://www.youtube.com/oembed"
          Patterns:
            - "https?://(?:[^\\.]+\\.)?youtube\\.com/watch/?\\?(?:.+&)?v=([^&]+)"
            - "https?://youtu\\.be/([a-zA-Z0-9_-]+)"
        # Default URL provider - should be last in the Providers list...
        - Name: default
          Type: DefaultUrl
          Patterns:
            - "https?://.*"
  Smtp:
    Assembly: httplib.mod.smtp.dll
    Typename: httplib.mod.Smtp
    Data:
      Host: localhost
      Port: 25
  Textile:
    Assembly: httplib.mod.textile.dll
    Typename: httplib.mod.Textile
MimeTypes:
  ico: image/x-icon
  js: application/javascript
  json: application/json
  html: text/html
  png: image/png
  css: text/css
  ttf: application/x-font-ttf
  woff: application/x-font-woff
  woff2: application/octet-stream
  _: text/plain
OutputLength: 800
FileChunkLength: 1024
ForceInsecureOperation: false
Logging:
  Assembly: httplib.log.nlog.dll
  Typename: httplib.log.NLogLogging
  Targets:
    console:
      Type: ColoredConsoleTarget
      Layout: "${message}"
      Colours: { Debug: DarkGreen, Info: Green, Warn: Cyan }
    file:
      Type: FileTarget
      Path: "${basedir}/forum-${date:format=yyyy.MM.dd-HH.mm.ss:cached=true}.log"
      Layout: "${date:format=HH\\:mm\\:ss} ${logger} ${message}"
    live:
      Type: FileTarget
      Path: "forum-live.log"
      Layout: "${date:format=yyyy.MM.dd HH\\:mm\\:ss} ${logger} ${message}"
      ReplaceFile: true
  Rules:
    - { Source: "*", Level: Trace, Target: console }
    - { Source: "*", Level: Info, Target: file }
    - { Source: "*", Level: Error, Target: live }
