# ------------------------------------------------------------------------------
# Example forum.exe configuration
---
Databases:
  default:
    Assembly: httplib.db.mysql.dll
    Typename: httplib.db.MySqlDatabase
    Connection: server=localhost;userid=forum;password=n0ts3cr3t;database=forum
Prefixes:
  Secure:
    - https://127.0.0.1:8443/
  Insecure:
    - http://localhost:8080/
Roots:
  - www
  - ../../contrib/client
  - ../../contrib/fonts
FileServing:
  /.*css: { Cache-Control: "public, max-age=86400" }
  /.*html: { Cache-Control: "no-cache" }
  /.*js: { Cache-Control: "private, max-age=86400" }
  /.*map: { Cache-Control: "public, max-age=86400" }
  /.*png: { Cache-Control: "public, max-age=86400" }
  /.*ttf: { Cache-Control: "public, max-age=31536000" }
  /.*woff: { Cache-Control: "public, max-age=31536000" }
  /.*woff2: { Cache-Control: "public, max-age=31536000" }
Renderers:
  yml:
    Assembly: httplib.dll
    Typename: httplib.Renderer
  nyml:
    Assembly: httplib.page.nustache.dll
    Typename: httplib.page.NustacheRenderer
Modules:
  - Assembly: forum.mod.filter.dll
    Typename: forum.mod.Filter
    Data:
      Filters:
        - { Search: "first post", Replace: "lame", Flags: "Boundary" }
        - { Search: "frist post", Replace: "lamer", Flags: "IgnoreCase|Boundary" }
        - { Search: "cock", Replace: "rooster", Flags: "IgnoreCase" }
        - { Search: "string", Replace: "chord", Flags: "IgnoreCase" }
  - Assembly: httplib.mod.auth.dll
    Typename: httplib.mod.Pbkdf2Auth
    Data:
      IterationCount: 25000
      HashLength: 40
  - Assembly: httplib.mod.bbcode.dll
    Typename: httplib.mod.BbCode
    Data:
      Tags:
        - { Tag: "b", Open: "<b>", Close: "</b>" }
        - { Tag: "i", Open: "<i>", Close: "</i>" }
        - { Tag: "u", Open: "<u>", Close: "</u>" }
        - { Tag: "s", Open: "<s>", Close: "</s>" }
        - { Tag: "tt", Open: "<tt>", Close: "</tt>" }
        - { Tag: "h1", Open: "<h1>", Close: "</h1>" }
        - { Tag: "h2", Open: "<h2>", Close: "</h2>" }
        - { Tag: "h3", Open: "<h3>", Close: "</h3>" }
        - { Tag: "h4", Open: "<h4>", Close: "</h4>" }
        - { Tag: "h5", Open: "<h5>", Close: "</h5>" }
        - { Tag: "h6", Open: "<h6>", Close: "</h6>" }
        - { Tag: "code", Open: "<pre>", Close: "</pre>" }
        - { Tag: "img", Open: "<img src='${content}'/>", Close: "", Flags: "NoAutoRender" }
        - { Tag: "quote", Open: "<blockquote>", Close: "</blockquote>" }
        - { Tag: "list", Open: "<ul>", Close: "</ul>" }
        - { Tag: "ul", Open: "<ul>", Close: "</ul>" }
        - { Tag: "ol", Open: "<ol>", Close: "</ol>" }
        - { Tag: "li", Open: "<li>", Close: "</li>" }
        - { Tag: "*", Open: "<li>", Close: "</li>", Flags: "NoClose" }
        - { Tag: "url", Open: "<a href='${href}'>", Close: "</a>",
            Attrs: [ { Id: "href", Name: "" }, { Id: "href", Name: "href" } ] }
  - Assembly: httplib.mod.htmlsanitize.dll
    Typename: httplib.mod.HtmlSanitizer
  - Assembly: httplib.mod.oembed.dll
    Typename: httplib.mod.OEmbed
  - Assembly: httplib.mod.textile.dll
    Typename: httplib.mod.Textile
MimeTypes:
  js: application/javascript
  json: application/json
  html: text/html
  css: text/css
  ttf: application/x-font-ttf
  woff: application/x-font-woff
  woff2: application/octet-stream
  _: text/plain
OutputLength: 800
FileChunkLength: 1024
Logging:
  Assembly: httplib.log.nlog.dll
  Typename: httplib.log.NLogLogging
  Targets:
    console:
      Type: ColoredConsoleTarget
      Layout: "${message}"
      Colours: { Debug: DarkGreen, Info: Green, Warn: Cyan }
    file:
      Type: FileTarget
      Path: "${basedir}/forum-${date:format=yyyyMMddHHmmss:cached=true}.log"
      Layout: "${date:format=HH\\:mm\\:ss} ${logger} ${message}"
  Rules:
    - { Source: "*", Level: Trace, Target: console }
    - { Source: "*", Level: Info, Target: file }
