# ------------------------------------------------------------------------------
# Example forum.exe configuration
---
Database:
  Assembly: httplib.db.mysql.dll
  Typename: httplib.db.MySqlDatabase
  Connection: server=localhost;userid=forum;password=n0ts3cr3t;database=forum
Prefixes:
  Secure:
    - https://localhost:8443/
  Insecure:
    - http://localhost:8080/
Roots:
  - ../src/forum/www
  - ../contrib/client
FileServing:
  - /.*css
  - /.*html
  - /.*js
  - /.*map
  - /.*png
  - /.*ttf
  - /.*woff
  - /.*woff2
Renderers:
  yml:
    Assembly: httplib.dll
    Typename: httplib.Renderer
  nyml:
    Assembly: httplib.page.nustache.dll
    Typename: httplib.page.NustacheRenderer
Modules:
  - Assembly: forum.mod.auth.dll
    Typename: forum.mod.Auth
  - Assembly: httplib.mod.bbcode.dll
    Typename: httplib.mod.BbCode
  - Assembly: httplib.mod.htmlsanitize.dll
    Typename: httplib.mod.HtmlSanitizer
  - Assembly: httplib.mod.oembed.dll
    Typename: httplib.mod.OEmbed
  - Assembly: httplib.mod.textile.dll
    Typename: httplib.mod.Textile
MimeTypes:
  js: application/javascript
  json: application/json
  html: text/html
  css: text/css
  ttf: application/x-font-ttf
  woff: application/x-font-woff
  woff2: application/octet-stream
  _: text/plain
OutputLength: 800
FileChunkLength: 1024
Logging:
  Assembly: httplib.log.nlog.dll
  Typename: httplib.log.NLogLogging
  Targets:
    console:
      Type: ColoredConsoleTarget
      Layout: "${message}"
      Colours: { Debug: DarkGreen, Info: Green, Warn: DarkYellow }
    file:
      Type: FileTarget
      Path: "${basedir}/forum-${date:format=yyyyMMddHHmmss:cached=true}.log"
      Layout: "${date:format=HH\\:mm\\:ss} ${logger} ${message}"
  Rules:
    - { Source: "*", Level: Trace, Target: console }
    - { Source: "*", Level: Info, Target: file }
